# -*- coding: utf-8 -*-
"""arima주가예측.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGDSSeZSNsapmyd1DXSy9eVmsoNpWsKr
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np

data = pd.read_csv('삼성0910.csv')



y = data.iloc[:,4]
X = data.iloc[:,0]
y = np.array(y[::-1])
X = np.array(X[::-1])

for i in range(len(y)):
  y[i]=int(y[i].replace(',',''))











from statsmodels.tsa.arima_model import ARIMA

model = ARIMA(y,(0,2,1))

model_fit = model.fit()

print(model_fit.summary())

output = model_fit.forecast(steps=4)

output[0]

