# -*- coding: utf-8 -*-
"""주가예측.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GUquEWEUavFmpQz_ABdSZEWXaCfa04YU
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np



data = pd.read_csv('samsung.csv')

data.iloc[0:3]

data.iloc[:575,1:6].isnull().sum()

label = np.array(data.iloc[:575,4])

x_data = np.array(data.iloc[:575,1:6])



label.shape

x_data.shape

x_data = x_data[::-1]
label = label[::-1]

for i in x_data:
  for j in range(5):
    i[j]=int(i[j].replace(',',''))

print(x_data[0:5], x_data[-5:])
for i in range(len(label)):
  label[i]=int(label[i].replace(',',''))

print(label[0:5], label[-5:])

from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
x_data = sc.fit_transform(x_data)

label = label/10000

x_data[0:5]

x_train_dataset = x_data[:-100]
x_test_dataset = x_data[-100:]
y_train_dataset = label[:-100]
y_test_dataset = label[-100:]

print(x_train_dataset.shape, x_test_dataset.shape, y_train_dataset.shape, y_test_dataset.shape)

# def slice_dataset(x,y,predict_date=7,period=20):
#   x_return = []
#   y_return = []
#   for i in range(len(x)-predict_date-period+1):
#     x_return.append(x[i:i+period])
#     y_return.append(y[i+period:i+period+predict_date])
#   return np.array(x_return), np.array(y_return)

def sd(x,y,period):
  x_return = []
  y_return = []
  x_last = []
  for i in range(len(x)-period):
    x_return.append(x[i:i+period])
    y_return.append(y[i+period])
  for i in range(len(x)-period+1):
    x_last.append(x[i:i+period])

  return np.array(x_return), np.array(y_return), np.array(x_last)

# predict_date = 1
# period = 40

# x_train, y_train = slice_dataset(x_train_dataset, y_train_dataset,
#                                  predict_date=predict_date,
#                                  period=period)

# x_test, y_test = slice_dataset(x_test_dataset, y_train_dataset,
#                                predict_date=predict_date,
#                                period=period)

x_train, y_train,_ = sd(x_train_dataset, y_train_dataset,30)

x_test, y_test, x_last = sd(x_test_dataset, y_test_dataset, 30)



print(x_train.shape,y_train.shape, x_test.shape, y_test.shape, x_last.shape)

print(x_last[-2:]-x_test[-1])

from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

model = Sequential()
model.add(LSTM(64,input_shape=(30,5), return_sequences=True))
model.add(LSTM(64))
model.add(Dropout(0.2))
model.add(Dense(32,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1))

model.summary()

es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=100)
mc = ModelCheckpoint('./best_model.h5', monitor='val_loss', mode='min',verbose=1, save_best_only=True)


model.compile(loss='mse',optimizer='adam')

model.fit(x_train, y_train, batch_size=10, epochs=500, validation_data=(x_test, y_test), callbacks=[es, mc])


model.load_weights('best_model.h5')

pre = model.predict(x_test)

for i in range(len(pre)):
  print(f'{32+i}일 | 실제값 : {y_test[i]}만원  |  예측값 : {float(pre[i])}만원 |    차이 : {100 - float(pre[i])/y_test[i]*100}%')

import matplotlib.pyplot as plt

fig = plt.figure(facecolor='white', figsize=(10, 4))
ax = fig.add_subplot(111)
ax.plot(y_test, label='Real')
ax.plot(pre, label='Predict')
ax.legend()
plt.show()

print(f'내일의 종가 예측 : {float(model.predict(x_last)[-1])} 만원')





















