# Generated by Django 3.0.7 on 2020-06-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('topic_idx', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('content_idx', models.AutoField(primary_key=True, serialize=False)),
                ('content_text', models.TextField()),
                ('content_topic_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TopicModel')),
            ],
        ),
    ]
