# Generated by Django 3.0.7 on 2020-06-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200608_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='content_topic_idx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.TopicModel'),
        ),
    ]
